remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ["FCV Data Collection Tutorials" ]
description: ["Learn the fundamentals of Remote Sensing, Drone, and Mobile data collection, and how to apply them to a range of FCV related projects"]

